#!/bin/bash
#
# chkconfig: 35 90 12
# description: mmdintegrator service
#
# Get function from functions library
. /etc/init.d/functions

# Start the service mmdintegrator
start() {
        initlog -c "echo -n Iniciando mmdintegrator: "
        /usr/local/bin/mmdintegrator  &
        pypid=$(pidof -x /usr/local/bin/mmdintegrator)
        touch /var/run/mmdintegrator.pid
	echo -n $pypid > /var/run/mmdintegrator.pid
	### Create the lock file ###
        touch /var/lock/subsys/mmdintegrator
        success $"iniciado correctamente"
        echo
}
# Restart the service mmdintegrator
stop() {
        initlog -c "echo -n Deteniendo mmdintegrator: "
	pypid=$(pidof -x /usr/local/bin/mmdintegrator)
	kill -9 $pypid
        ### Now, delete the lock file ###
        rm -f /var/lock/subsys/mmdintegrator
	rm -f /var/run/mmdintegrator.pid
        echo
}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status mmdintegrator
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0